[2022-04-26 01:19:58,332] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: starwarapi.transform_load scheduled__2022-04-26T00:40:25.850955+00:00 [queued]>
[2022-04-26 01:19:58,930] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: starwarapi.transform_load scheduled__2022-04-26T00:40:25.850955+00:00 [queued]>
[2022-04-26 01:19:58,935] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-26 01:19:58,939] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-26 01:19:58,946] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-26 01:19:59,193] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform_load> on 2022-04-26 00:40:25.850955+00:00
[2022-04-26 01:19:59,468] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2022-04-26 01:19:59,513] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'starwarapi', 'transform_load', 'scheduled__2022-04-26T00:40:25.850955+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/starwar_dag.py', '--cfg-path', '/tmp/tmpbsqqvijv', '--error-file', '/tmp/tmpmhh_ym2b']
[2022-04-26 01:19:59,529] {standard_task_runner.py:80} INFO - Job 32: Subtask transform_load
[2022-04-26 01:20:01,116] {logging_mixin.py:109} INFO - Running <TaskInstance: starwarapi.transform_load scheduled__2022-04-26T00:40:25.850955+00:00 [running]> on host 66327e1a8873
[2022-04-26 01:20:01,878] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=starwarapi
AIRFLOW_CTX_TASK_ID=transform_load
AIRFLOW_CTX_EXECUTION_DATE=2022-04-26T00:40:25.850955+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-26T00:40:25.850955+00:00
[2022-04-26 01:20:50,536] {python.py:175} INFO - Done. Returned value was: None
[2022-04-26 01:20:52,289] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=starwarapi, task_id=transform_load, execution_date=20220426T004025, start_date=20220426T011958, end_date=20220426T012052
[2022-04-26 01:20:54,826] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-04-26 01:20:54,994] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 173. PIDs of all processes in the group: [173]
[2022-04-26 01:20:55,042] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 173
[2022-04-26 01:20:55,321] {process_utils.py:70} INFO - Process psutil.Process(pid=173, status='terminated', exitcode=0, started='01:19:58') (173) terminated with exit code 0
