[2022-04-26 01:19:52,517] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: starwarapi.transform_load scheduled__2022-04-26T00:45:34.862951+00:00 [queued]>
[2022-04-26 01:19:53,098] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: starwarapi.transform_load scheduled__2022-04-26T00:45:34.862951+00:00 [queued]>
[2022-04-26 01:19:53,105] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-26 01:19:53,153] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-26 01:19:53,161] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-26 01:19:53,889] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform_load> on 2022-04-26 00:45:34.862951+00:00
[2022-04-26 01:19:54,112] {standard_task_runner.py:52} INFO - Started process 166 to run task
[2022-04-26 01:19:54,205] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'starwarapi', 'transform_load', 'scheduled__2022-04-26T00:45:34.862951+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/starwar_dag.py', '--cfg-path', '/tmp/tmpocfg7qaf', '--error-file', '/tmp/tmpa_swceho']
[2022-04-26 01:19:54,216] {standard_task_runner.py:80} INFO - Job 28: Subtask transform_load
[2022-04-26 01:19:55,756] {logging_mixin.py:109} INFO - Running <TaskInstance: starwarapi.transform_load scheduled__2022-04-26T00:45:34.862951+00:00 [running]> on host 66327e1a8873
[2022-04-26 01:19:56,716] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=starwarapi
AIRFLOW_CTX_TASK_ID=transform_load
AIRFLOW_CTX_EXECUTION_DATE=2022-04-26T00:45:34.862951+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-26T00:45:34.862951+00:00
[2022-04-26 01:20:50,511] {python.py:175} INFO - Done. Returned value was: None
[2022-04-26 01:20:52,156] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=starwarapi, task_id=transform_load, execution_date=20220426T004534, start_date=20220426T011952, end_date=20220426T012052
[2022-04-26 01:20:55,220] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-04-26 01:20:55,679] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 166. PIDs of all processes in the group: [166]
[2022-04-26 01:20:56,163] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 166
[2022-04-26 01:20:56,173] {process_utils.py:70} INFO - Process psutil.Process(pid=166, status='terminated', exitcode=0, started='01:19:53') (166) terminated with exit code 0
