[2022-04-25 19:39:52,208] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: starwarapi.extract scheduled__2022-04-25T19:37:58.834715+00:00 [queued]>
[2022-04-25 19:39:52,394] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: starwarapi.extract scheduled__2022-04-25T19:37:58.834715+00:00 [queued]>
[2022-04-25 19:39:52,401] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 19:39:52,405] {taskinstance.py:1250} INFO - Starting attempt 2 of 2
[2022-04-25 19:39:52,409] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 19:39:52,641] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-25 19:37:58.834715+00:00
[2022-04-25 19:39:52,725] {standard_task_runner.py:52} INFO - Started process 112 to run task
[2022-04-25 19:39:52,773] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'starwarapi', 'extract', 'scheduled__2022-04-25T19:37:58.834715+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/starwar_dag.py', '--cfg-path', '/tmp/tmp4nt9dtp1', '--error-file', '/tmp/tmpk2qm0xgr']
[2022-04-25 19:39:52,776] {standard_task_runner.py:80} INFO - Job 124: Subtask extract
[2022-04-25 19:39:55,227] {logging_mixin.py:109} INFO - Running <TaskInstance: starwarapi.extract scheduled__2022-04-25T19:37:58.834715+00:00 [running]> on host e1b1812bbeeb
[2022-04-25 19:39:55,783] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=starwarapi
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-25T19:37:58.834715+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-25T19:37:58.834715+00:00
[2022-04-25 19:39:56,346] {logging_mixin.py:109} INFO - <Response [200]>
[2022-04-25 19:39:56,372] {python.py:175} INFO - Done. Returned value was: <Response [200]>
[2022-04-25 19:39:56,481] {xcom.py:448} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-04-25 19:39:56,486] {taskinstance.py:1747} WARNING - We expected to get frame set in local storage but it was not. Please report this as an issue with full logs at https://github.com/apache/***/issues/new
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1340, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1477, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1544, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2207, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1741, in get_truncated_error_traceback
    execution_frame = _TASK_EXECUTION_FRAME_LOCAL_STORAGE.frame
AttributeError: '_thread._local' object has no attribute 'frame'
[2022-04-25 19:39:56,504] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1340, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1477, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1544, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2207, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2022-04-25 19:39:56,572] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=starwarapi, task_id=extract, execution_date=20220425T193758, start_date=20220425T193952, end_date=20220425T193956
[2022-04-25 19:39:56,667] {standard_task_runner.py:98} ERROR - Failed to execute job 124 for task extract (Object of type Response is not JSON serializable; 112)
[2022-04-25 19:39:56,796] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 19:39:57,076] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
